// =============================================================
// TAIWAN BAR BIBLE — 酒吧資料庫（依縣市分段）
// 欄位說明（除 name/city 外皆可省略，省略的欄位卡片上自動隱藏）：
//   name: 店名          city: 縣市        district: 行政區
//   type: 經典|特調|經典特調|啤酒          purpose: 一個人|聚會|聚會或一個人
//   style: 風格（日式、Speakeasy、茶酒…）  price: 1~3（$~$$$）
//   address / phone / hours: 地址、電話、營業時間
//   rating / ratingCount: Google 星等與評論數（整理時參考值）
//   awards: ["獲獎紀錄"]   special: true=私心推薦   note: 介紹或註記
// 新增酒吧：在對應縣市段落照格式加一行即可，網頁會自動歸類與計數。
// =============================================================
const BARS = [

  // ───── 台北市 ─────
  {name: "隧道", city: "台北市", district: "內湖區", type: "經典", purpose: "聚會", note: "在地的local酒吧｜便宜"},
  {name: "小後苑 大直", city: "台北市", district: "中山區", type: "經典", purpose: "聚會或一個人", note: "偏商務，不便宜"},
  {name: "如詩", city: "台北市", district: "中山區", type: "特調", purpose: "聚會或一個人", note: "適合約會"},
  {name: "BAR DI", city: "台北市", district: "中山區", type: "經典", purpose: "聚會或一個人", note: "適合約會｜英迪格酒店四樓｜脆友推薦"},
  {name: "INGE'S Bar & Grill", city: "台北市", district: "中山區", type: "經典", purpose: "聚會或一個人", note: "適合約會｜萬豪酒店二十樓｜脆友推薦"},
  {name: "the Weekend Nights", city: "台北市", district: "內湖區", type: "經典特調", purpose: "聚會或一個人", note: "長島很濃"},
  {name: "Art bar 藝術家的酒吧", city: "台北市", district: "北投區", type: "特調", purpose: "聚會或一個人", note: "Speakeasy｜脆友推薦"},
  {name: "酉茶提案", city: "台北市", district: "士林區", type: "特調", purpose: "聚會或一個人", note: "茶酒為主，可請老闆infuse一支"},
  {name: "Bar DAD", city: "台北市", district: "士林區", type: "經典特調", purpose: "聚會", note: "老吧老闆，脆友推薦"},
  {name: "wake up bar", city: "台北市", district: "士林區", type: "經典", purpose: "聚會", note: "音樂人友善｜我喝完隔天會頭痛？"},
  {name: "Dobar", city: "台北市", district: "士林區", type: "經典", purpose: "聚會", note: "脆友推薦"},
  {name: "Ole Rum Bar 2F", city: "台北市", district: "士林區", type: "經典特調", purpose: "聚會", note: "專業蘭姆酒吧｜脆友推薦"},
  {name: "覓到by bar mood", city: "台北市", district: "中山區", type: "經典特調", purpose: "聚會", note: "適合約會｜地點超酷"},
  {name: "綠門老酒吧", city: "台北市", district: "中山區", type: "特調", purpose: "聚會", note: "在地的local酒吧｜老派約會"},
  {name: "Bar Outlander", city: "台北市", district: "中山區", type: "特調", purpose: "聚會", note: "脆友推薦但評價兩極"},
  {name: "Bar ansleep Taipei", city: "台北市", district: "中山區", type: "經典", purpose: "聚會或一個人", note: "日本調酒師回國ㄌ🥲"},
  {name: "BAR 忠", city: "台北市", district: "中山區", type: "經典", purpose: "一個人", special: true, note: "日本調酒師｜真材實料｜行天宮三本柱"},
  {name: "心白", city: "台北市", district: "中山區", type: "經典", purpose: "聚會", special: true, note: "清酒吧｜餐點好吃｜行天宮三本柱"},
  {name: "Light House", city: "台北市", district: "中山區", type: "經典", purpose: "聚會或一個人", special: true, note: "四訪驚喜｜去就對了｜行天宮三本柱"},
  {name: "奏 ZOU Listening Bar", city: "台北市", district: "大同區", type: "經典", purpose: "聚會或一個人", note: "脆友推薦"},
  {name: "小小間酒吧", city: "台北市", district: "大同區", type: "經典", purpose: "一個人", note: "脆友推薦"},
  {name: "Como Tú", city: "台北市", district: "大同區", type: "經典", purpose: "一個人", note: "酒友推薦"},
  {name: "ASABAN", city: "台北市", district: "大同區", type: "特調", purpose: "一個人", note: "下午開喝｜預約制茶酒｜富錦樹老闆推薦"},
  {name: "小城外", city: "台北市", district: "大同區", type: "經典", purpose: "一個人", note: "咖啡酒吧"},
  {name: "蟬 Bar", city: "台北市", district: "大同區", type: "特調", purpose: "聚會", note: "適合約會｜酒友說還好😂"},
  {name: "玉露", city: "台北市", district: "大同區", type: "經典特調", purpose: "聚會", note: "茶經典一定要試｜去過兩次非常喜歡"},
  {name: "BarWay", city: "台北市", district: "大同區", type: "經典", purpose: "一個人", note: "下午就可以開喝"},
  {name: "Wang Tea Taipei 有記名茶", city: "台北市", district: "大同區", type: "啤酒", purpose: "聚會", note: "下午開喝茶啤"},
  {name: "同位素", city: "台北市", district: "大同區", type: "經典特調", purpose: "聚會或一個人", note: "裝潢歐洲感｜天穹漂亮"},
  {name: "Bitter Burro Cocktail Bar", city: "台北市", district: "大同區", type: "特調", purpose: "聚會", note: "酒友推薦"},
  {name: "Tik & Sip Wine Bar", city: "台北市", district: "萬華區", type: "經典", purpose: "聚會", note: "下午喝紅白酒｜適合約會"},
  {name: "桃花源", city: "台北市", district: "中正區", type: "經典", purpose: "聚會", note: "長島好喝｜店員人超好直補酒精"},
  {name: "萬華世界下午酒場", city: "台北市", district: "萬華區", type: "特調", purpose: "聚會", note: "下午開喝｜啤酒愛好者推"},
  {name: "DUO Taipei", city: "台北市", district: "萬華區", type: "特調", purpose: "聚會", note: "便宜｜脆友推薦"},
  {name: "老吧 Bar", city: "台北市", district: "中山區", type: "特調", purpose: "聚會", note: "辛拉麵必吃｜空間小"},
  {name: "Book ing", city: "台北市", district: "大同區", type: "特調", purpose: "聚會", note: "脆友推薦"},
  {name: "Bar Soft Cure", city: "台北市", district: "中山區", type: "經典特調", purpose: "一個人", note: "吧台位｜黑膠音樂｜很讚"},
  {name: "Bar Turning Point", city: "台北市", district: "中山區", type: "經典", purpose: "一個人", note: "日本調酒師｜安靜場合"},
  {name: "Mini Base 小喬室", city: "台北市", district: "中山區", type: "特調", purpose: "聚會", note: "酒跟shot偏甜｜CP值高"},
  {name: "澤山", city: "台北市", district: "中山區", type: "特調", purpose: "一個人", note: "酒吧pairing等級"},
  {name: "MUD Bar", city: "台北市", district: "中山區", type: "特調", purpose: "聚會", note: "空間超大｜有DJ"},
  {name: "Bar Impromptu", city: "台北市", district: "中山區", type: "經典特調", purpose: "一個人", note: "曾經愛店｜調酒師離開了"},
  {name: "銀座酒向", city: "台北市", district: "中山區", type: "經典", purpose: "聚會或一個人", note: "日式｜日本調酒師｜低消800"},
  {name: "Bar Gravit.on 烏寂重子", city: "台北市", district: "中山區", type: "經典特調", purpose: "聚會", note: "酒友推薦"},
  {name: "小谷", city: "台北市", district: "中山區", type: "經典", purpose: "一個人", note: "日式｜日本調酒師"},
  {name: "Bar 千華", city: "台北市", district: "中山區", type: "經典", purpose: "聚會或一個人", note: "開到六點｜麻婆豆腐讚"},
  {name: "ETNA", city: "台北市", district: "中山區", type: "特調", purpose: "聚會或一個人", note: "可以抽煙｜不喜煙味跳過"},
  {name: "Bar Kawa 川", city: "台北市", district: "中山區", type: "經典特調", purpose: "聚會或一個人", note: "脆友推薦"},
  {name: "試營運", city: "台北市", district: "中山區", type: "經典", purpose: "一個人", note: "地圖找重本書店｜酒友推薦"},
  {name: "Bar Yoshi 梄時", city: "台北市", district: "中山區", type: "特調", purpose: "聚會", note: "水餃不錯｜酒單用心"},
  {name: "Lounge Vino", city: "台北市", district: "中山區", type: "特調", purpose: "聚會", note: "夜景氣氛好｜適合約會"},
  {name: "HiBoRu", city: "台北市", district: "中山區", type: "特調", purpose: "聚會", awards: ["2026 Spirited Awards 全球十強入圍"], note: "台式復古｜東西好吃｜適合首站"},
  {name: "Bar春花", city: "台北市", district: "中正區", type: "經典", purpose: "一個人", note: "調酒師好聊｜喜歡互動坐吧台"},
  {name: "Vent", city: "台北市", district: "中山區", type: "經典", purpose: "一個人", note: "春花二店｜風格韓系"},
  {name: "故地", city: "台北市", district: "中山區", type: "特調", purpose: "聚會", note: "有店貓｜酒中規中矩"},
  {name: "洞香春", city: "台北市", district: "松山區", type: "特調", purpose: "聚會", note: "脆友推薦"},
  {name: "Honn Bar", city: "台北市", district: "中山區", type: "特調", purpose: "聚會", note: "前老闆開的"},
  {name: "THE BAR酒吧", city: "台北市", district: "中山區", type: "經典", purpose: "聚會", note: "JR飯店內｜談生意首選"},
  {name: "M O. Bar", city: "台北市", district: "松山區", type: "經典", purpose: "聚會", note: "文華東方內｜脆友推薦"},
  {name: "Cooper", city: "台北市", district: "松山區", type: "經典", purpose: "聚會", note: "適合約會｜調酒師推薦"},
  {name: "The Glasshouse", city: "台北市", district: "松山區", type: "經典", purpose: "聚會", note: "適合約會｜脆友推薦"},
  {name: "異塵", city: "台北市", district: "松山區", type: "經典", purpose: "聚會", note: "脆友推薦"},
  {name: "Histoire 隅意", city: "台北市", district: "松山區", type: "特調", purpose: "聚會", note: "脆友推薦"},
  {name: "OriginBAR 源", city: "台北市", district: "松山區", type: "特調", purpose: "聚會", note: "茶酒連鎖"},
  {name: "台北酒驛", city: "台北市", district: "松山區", type: "經典特調", purpose: "聚會", note: "脆友推薦"},
  {name: "HI NE NI", city: "台北市", district: "中正區", type: "特調", purpose: "聚會", note: "音樂讚｜脆友推薦"},
  {name: "Bar M", city: "台北市", district: "中正區", type: "經典", purpose: "聚會", note: "威士忌/琴酒多｜偏日系｜愛店"},
  {name: "Arman", city: "台北市", district: "中正區", type: "經典", purpose: "一個人", note: "酒友推薦｜待訪"},
  {name: "Staff Only Club", city: "台北市", district: "中正區", type: "經典特調", purpose: "聚會", note: "酒友推薦"},
  {name: "一茶一瓦", city: "台北市", district: "松山區", type: "特調", purpose: "聚會", note: "室內版Draft Land｜氣氛強"},
  {name: "IMBIBE", city: "台北市", district: "大安區", type: "特調", purpose: "聚會", note: "創意強烈｜吃重口味"},
  {name: "Bar Pulse", city: "台北市", district: "松山區", type: "經典", purpose: "聚會", note: "酒友推薦"},
  {name: "寓曰", city: "台北市", district: "大安區", type: "經典", purpose: "聚會", note: "薯條很讚？｜脆友推薦"},
  {name: "傷心酒店", city: "台北市", district: "松山區", type: "特調", purpose: "聚會", note: "台北名店｜氣氛不錯"},
  {name: "三藩市", city: "台北市", district: "大安區", type: "經典特調", purpose: "聚會", note: "實力硬"},
  {name: "BAR MOOD", city: "台北市", district: "大安區", type: "經典特調", purpose: "聚會", awards: ["Asia's 50 Best Bars 2024 #37"], note: "台北名店"},
  {name: "OAK", city: "台北市", district: "大安區", type: "經典特調", purpose: "聚會", note: "調酒師推薦"},
  {name: "Cozy", city: "台北市", district: "大安區", type: "特調", purpose: "聚會", note: "餐點好吃｜老闆像杰倫"},
  {name: "崎白湯屋", city: "台北市", district: "大安區", type: "經典", purpose: "聚會或一個人", note: "三得利開的｜日威愛好者推"},
  {name: "To Infinity & Beyond", city: "台北市", district: "大安區", type: "經典", purpose: "聚會或一個人", awards: ["Asia's 50 Best Bars 2025 #41"], note: "50大酒吧常客"},
  {name: "Kitty Taipei", city: "台北市", district: "大安區", type: "特調", purpose: "聚會", note: "蜂蜜雞翅/沙拉必點｜餐點超好吃"},
  {name: "羊吧", city: "台北市", district: "信義區", type: "特調", purpose: "一個人", note: "紅白酒/清酒多｜脆友推薦"},
  {name: "Bar Weekend", city: "台北市", district: "大安區", type: "經典特調", purpose: "聚會或一個人", special: true, note: "我的台北前五名"},
  {name: "INDULGE", city: "台北市", district: "大安區", type: "經典特調", purpose: "聚會或一個人", awards: ["Asia's 50 Best Bars 2024 #11","World's 50 Best Bars 2019 #21"], note: "台北名店"},
  {name: "深杯子", city: "台北市", district: "大安區", type: "經典特調", purpose: "一個人", note: "脆友推薦"},
  {name: "Drizzle by Fourplay", city: "台北市", district: "大安區", type: "經典特調", purpose: "聚會", note: "脆友推薦"},
  {name: "Monkie", city: "台北市", district: "大安區", type: "經典特調", purpose: "聚會", note: "脆友推薦"},
  {name: "Testing Room", city: "台北市", district: "大安區", type: "特調", purpose: "聚會", note: "Draft Land 2F｜隱藏感"},
  {name: "Cog & J", city: "台北市", district: "大安區", type: "特調", purpose: "聚會", note: "unDer lab樓上"},
  {name: "unDer lab", city: "台北市", district: "大安區", type: "特調", purpose: "聚會", awards: ["Asia's 50 Best Bars 2025 #73"], note: "創意調酒｜吃當季酒單"},
  {name: "Lab", city: "台北市", district: "大安區", type: "經典特調", purpose: "一個人", awards: ["Asia's 50 Best Bars 2025 #57"], note: "個人偏愛Lab派"},
  {name: "MONO MONO", city: "台北市", district: "大安區", type: "特調", purpose: "聚會", note: "脆友推薦"},
  {name: "Mizu Bistro", city: "台北市", district: "大安區", type: "特調", purpose: "聚會", note: "新開幕冷門"},
  {name: "YiYi 液藝", city: "台北市", district: "大安區", type: "特調", purpose: "一個人", note: "咖啡酒吧｜小眾"},
  {name: "The Fridge bar", city: "台北市", district: "信義區", type: "特調", purpose: "一個人", note: "冰箱門入口｜炸雞比酒紅"},
  {name: "晨箔", city: "台北市", district: "大安區", type: "特調", purpose: "一個人", note: "銀波二店｜拉麵必吃"},
  {name: "Bar Between", city: "台北市", district: "大安區", type: "經典", purpose: "一個人", special: true, note: "日本調酒師｜台北前五名"},
  {name: "Bar Three Piece", city: "台北市", district: "信義區", type: "經典", purpose: "一個人", note: "日本調酒師｜精緻秀氣"},
  {name: "Liowl", city: "台北市", district: "大安區", type: "經典", purpose: "一個人", note: "有貓｜資深酒客推"},
  {name: "ACDC Taipei", city: "台北市", district: "信義區", type: "經典", purpose: "聚會", note: "室內版Fake Sober｜熱鬧"},
  {name: "Knock Knock", city: "台北市", district: "大安區", type: "特調", purpose: "聚會", note: "食物系調酒"},
  {name: "The Public House", city: "台北市", district: "大安區", type: "經典", purpose: "聚會", awards: ["Asia's 50 Best Bars 2025 #40"], note: "食物超讚｜頂級雞湯｜推經典"},
  {name: "半路餐酒", city: "台北市", district: "大安區", type: "特調", purpose: "聚會", note: "火鍋酒必點｜重酒感"},
  {name: "Bar Pine", city: "台北市", district: "大安區", type: "特調", purpose: "一個人", note: "山苦瓜Gin Fizz大推"},
  {name: "PUN", city: "台北市", district: "大安區", type: "特調", purpose: "聚會", awards: ["Nest by PUN 獲 Asia's 50 Best Bars 2024 最佳酒單獎"], note: "Speakeasy名店"},
  {name: "晃", city: "台北市", district: "大安區", type: "特調", purpose: "聚會或一個人", note: "酒友推薦"},
  {name: "Sidebar", city: "台北市", district: "大安區", type: "經典", purpose: "聚會或一個人", note: "琴酒吧名店"},
  {name: "芏", city: "台北市", district: "大安區", type: "經典特調", purpose: "一個人", note: "下午開喝｜冷門經典多"},
  {name: "SOIL", city: "台北市", district: "大安區", type: "經典特調", purpose: "一個人", note: "富錦樹/日本調酒師"},
  {name: "Suki Salon", city: "台北市", district: "大安區", type: "經典特調", purpose: "一個人", note: "日式Mixology"},
  {name: "Futura by TPH", city: "台北市", district: "大安區", type: "經典特調", purpose: "一個人", note: "公屋二店｜文青風"},
  {name: "Zoo KeepeR", city: "台北市", district: "大安區", type: "特調", purpose: "聚會", note: "有柯基｜動物主題｜適合約會"},
  {name: "Kashoku", city: "台北市", district: "大安區", type: "經典", purpose: "一個人", note: "老酒鬼推薦"},
  {name: "Bar Way Home", city: "台北市", district: "大安區", type: "經典", purpose: "聚會或一個人", note: "英倫風｜水準穩"},
  {name: "BBAR HINOKI", city: "台北市", district: "信義區", type: "經典", purpose: "一個人", note: "老酒鬼最後淨土"},
  {name: "tei by OBOND", city: "台北市", district: "信義區", type: "特調", purpose: "聚會", note: "入門儀式炫｜茶酒讚"},
  {name: "無 Wu (Nothingness)", city: "台北市", district: "信義區", type: "經典", purpose: "一個人", style: "無菜單經典調酒、極簡吧檯", price: 2, address: "台北市信義區光復南路419-1號1樓", hours: "19:00–01:00（低消600、僅收現金、不訂位）", awards: ["Asia's 50 Best Bars 2025 #66"], note: "World Class 亞太冠軍尹德凱的經典調酒吧，只做經典不走花俏，以台灣烈酒與食材重新詮釋老酒譜。"},
  {name: "AHA Saloon", city: "台北市", district: "大安區", type: "特調", purpose: "聚會或一個人", style: "美式沙龍、創意雞尾酒", price: 2, address: "台北市大安區復興南路二段138號", phone: "02-2706-5206", hours: "20:00–02:00（週一休，當日18:30後電話預約）", awards: ["Asia's 50 Best Bars 2021 #10"], note: "台北指標性創意調酒吧，曾登上亞洲50大酒吧前十名，以概念式酒單與高完成度特調著稱。"},
  {name: "MAD:MEN 面麵酒屋", city: "台北市", district: "大安區", type: "特調", purpose: "聚會", style: "摩登居酒屋、麵配調酒", price: 2, address: "台北市大安區和平東路三段68號1樓", hours: "18:00–02:00（週二休，低消500）", awards: ["2025 Spirited Awards 亞太區十強"], note: "Le Kief 創辦人打造的深夜摩登居酒屋，以自製中華麵、精緻下酒菜搭配調酒，獲調酒界奧斯卡亞太區十強肯定。"},

  // ───── 新北市 ─────
  {name: "多崎作 — The Ferrymen", city: "新北市", district: "淡水區", type: "特調", purpose: "聚會或一個人", note: "淡水人推薦｜便宜"},
  {name: "瀑布隔壁Bar", city: "新北市", district: "瑞芳區", type: "特調", purpose: "聚會", note: "適合約會｜地點超酷｜脆友推薦"},
  {name: "Chill Home 邱宅", city: "新北市", district: "樹林區", type: "經典特調", purpose: "聚會", note: "脆友推薦"},
  {name: "CAJU", city: "新北市", district: "板橋區", type: "特調", purpose: "聚會", note: "適合約會｜脆友推薦"},
  {name: "Bar Aku", city: "新北市", district: "板橋區", type: "特調", purpose: "聚會", note: "脆友推薦"},
  {name: "Bar Ripple", city: "新北市", district: "永和區", type: "特調", purpose: "聚會或一個人", note: "脆友推薦"},

  // ───── 基隆市 ─────
  {name: "Bad Mama 黑媽", city: "基隆市", district: "仁愛區", type: "經典特調", purpose: "聚會或一個人", style: "百年老宅、澳式酒吧餐館", price: 2, address: "基隆市仁愛區孝一路34巷5號", phone: "02-2425-6262", hours: "週二至週四 18:00–01:00（週日一休）", note: "150年紅磚古厝改造，吧台以整艘廢棄漁船打造，被多家媒體譽為世界級設計酒吧，兼營異國料理與花式調酒。"},
  {name: "艾克猴 The Alcohol Bar", city: "基隆市", district: "仁愛區", type: "經典特調", purpose: "聚會或一個人", style: "無酒單威士忌吧", price: 2, address: "基隆市仁愛區忠一路3巷23號", phone: "02-2425-2795", hours: "週一至四 20:00–01:00、週五六 19:00–02:00", note: "基隆代表性威士忌酒吧，藏酒六百至九百款威士忌，無制式酒單，調酒師依客人口感喜好客製調酒。"},
  {name: "EAT WIN 食運糖水鋪", city: "基隆市", district: "仁愛區", type: "特調", purpose: "聚會或一個人", style: "港式復古糖水鋪風", price: 2, address: "基隆市仁愛區仁四路13之1號1樓", phone: "0981-261-163", hours: "20:00–03:00（週一休）", note: "還原八零年代香港糖水鋪氛圍，紅綠霓虹燈極具特色，白天賣港式甜點、深夜化身酒吧，基隆深夜小酌名店。"},
  {name: "Squid Bar 魷魚啤酒吧", city: "基隆市", district: "仁愛區", type: "啤酒", purpose: "聚會或一個人", style: "精釀啤酒吧、外食友善", address: "基隆市仁愛區愛三路98巷18號1樓", hours: "16:00–24:00（不定休）", note: "廟口夜市旁的人氣精釀啤酒吧，主打本土精釀與自製披薩，可攜帶夜市外食入內，常有各國郵輪工作者造訪。"},
  {name: "避風港精釀 Haven Taproom & Bottle Shop", city: "基隆市", district: "仁愛區", type: "啤酒", purpose: "聚會或一個人", style: "精釀啤酒吧、賽事直播", address: "基隆市仁愛區愛三路98巷5號1樓", phone: "02-2428-0411", hours: "16:00–00:00（不定休）", note: "基隆廟口98巷內的精釀啤酒專門店，匯集全球精釀酒款並常態轉播體育賽事，外食友善，在地下班微醺聖地。"},

  // ───── 桃園市 ─────
  {name: "陸小曼 Lounge Bar", city: "桃園市", district: "中壢區", type: "經典特調", purpose: "聚會", style: "老牌 Lounge Bar", price: 2, address: "桃園市中壢區中央西路一段76巷33號", phone: "03-426-1212", hours: "21:00–04:00", note: "中壢開業超過十年的老牌酒吧，以經典調酒為底變化出多樣特調，設有飛鏢機與遊戲機台，平日也常座無虛席。"},
  {name: "NOT Bar & bistro", city: "桃園市", district: "中壢區", type: "特調", purpose: "聚會或一個人", style: "黑貓主題餐酒館", price: 2, address: "桃園市中壢區復興路28號", phone: "03-426-5299", hours: "週二至日 18:00–01:30（週五六至02:30，週一休）", awards: ["招牌「冠軍之路」獲波蘭調酒賽事第一名"], note: "中壢車站附近的黑貓主題酒吧，融合風味感知與飲食科學的創意調酒，酒單每季更新並融入台式古早風味。"},
  {name: "老石上", city: "桃園市", district: "中壢區", type: "特調", purpose: "一個人", style: "無酒單客製調酒", price: 3, address: "桃園市中壢區中北路二段211號", phone: "0920-330-890", hours: "20:00–01:30（週二休）", note: "中壢知名無酒單 Bar，客人只需描述喜好與口感，調酒師即客製專屬調酒，Google 評價近滿分。"},
  {name: "DramYouth Whisky Bar", city: "桃園市", district: "中壢區", type: "經典", purpose: "一個人", style: "威士忌吧", address: "桃園市中壢區大同路70號2樓", hours: "19:00–02:00", note: "被稱為中壢喝威士忌的天堂，收藏許多特殊少見的威士忌，超長吧台與柔和燈光空間舒適，也供應調酒。"},
  {name: "藏匿 Hide out Lounge Bar & Bistro", city: "桃園市", district: "中壢區", type: "特調", purpose: "聚會", style: "公園旁餐酒館、花式調酒", price: 2, address: "桃園市中壢區中美路76-10號", phone: "03-280-7351", hours: "18:00–01:30", note: "藏身中壢中正公園旁的老牌餐酒館，調酒師曾於國外獲獎，可欣賞花式甩酒表演，義大利麵與燉飯也頗受好評。"},
  {name: "醉生夢室", city: "桃園市", district: "中壢區", type: "特調", purpose: "聚會", style: "台式餐酒館、Shot 主題", price: 2, address: "桃園市中壢區中華路一段859號", phone: "03-451-2122", hours: "19:00–02:00（週一休）", note: "中壢人氣台式餐酒館，主打 Shot 調酒與台式料理，並有 KTV、飛鏢等娛樂設施，桃園高討論度的聚會酒吧。"},
  {name: "El Jardín Cocktail Bar", city: "桃園市", district: "桃園區", type: "經典特調", purpose: "聚會或一個人", style: "摩登復古調酒吧", price: 2, address: "桃園市桃園區經國路70號", phone: "03-316-0023", hours: "20:00–02:00（週五六至03:00，週四休）", rating: 4.5, ratingCount: 256, awards: ["台灣酒吧產業大獎 TBIA 多屆北區最佳酒吧"], note: "桃園必訪的專業調酒聖地，主理人溫哥人稱「香料魔術師」，供應經典調酒與四季獨創酒款，招牌如「正山走小路」。"},
  {name: "Jellyfish Bistro & Bar 水母餐酒館", city: "桃園市", district: "桃園區", type: "特調", purpose: "聚會", style: "水母主題餐酒館", price: 2, address: "桃園市桃園區復興路262號", phone: "03-338-2020", hours: "17:00–02:00（週一休）", note: "全台第一家以水母為主題的餐酒館，整面活水母魚缸牆搭配浮誇造型調酒，桃園火車站周邊打卡名店。"},
  {name: "BAR SPEAKEASY II", city: "桃園市", district: "桃園區", type: "經典特調", purpose: "聚會或一個人", style: "Speakeasy、老宅英式復古", price: 2, address: "桃園市桃園區公六街21號", phone: "03-331-5900", hours: "20:00–04:00", note: "源自新竹知名品牌 BAR SPEAKEASY 的二號店，藏身朝陽森林公園旁老宅，主打客製化調酒與復古氛圍，營業至凌晨四點。"},

  // ───── 新竹市 ─────
  {name: "Bar Back Cafe", city: "新竹市", district: "東區", type: "特調", purpose: "聚會或一個人", style: "老宅洋樓、咖啡×分子調酒", price: 2, address: "新竹市東區民權路111巷1號", phone: "03-5350226", hours: "約 16:00–00:00", note: "隱身巨城商圈巷內老洋樓，白天是手沖精品咖啡廳、晚上化身酒吧，以科學方法萃取食材香氣的實驗性分子調酒聞名。"},
  {name: "Tender Cocktail Bar", city: "新竹市", district: "北區", type: "經典特調", purpose: "聚會或一個人", style: "Speakeasy、台味調酒", price: 2, address: "新竹市北區經國路一段542號2樓", phone: "03-5335003", hours: "週日二至四 20:00–02:00；週五六至03:00（週一休）", note: "需按下「緊急求救按鈕」才能進入的隱藏式酒吧，以台灣素材原創調酒與地下樂團音樂文化聞名，訂位常滿需提前預約。"},
  {name: "BAR SPEAKEASY", city: "新竹市", district: "北區", type: "經典特調", purpose: "聚會或一個人", style: "美式藏酒博物館風", price: 2, address: "新竹市北區經國路二段587號", phone: "03-5268520", hours: "約 20:00–04:00", note: "2013年創立的新竹老牌酒吧，店內陳列近千款藏酒宛如酒類博物館，以6種基酒×7種風味的高度客製化調酒著稱，營業至凌晨四點。"},
  {name: "Bar Approx. 將進酒", city: "新竹市", district: "東區", type: "經典特調", purpose: "聚會或一個人", style: "中國風茶酒", price: 2, address: "新竹市東區金山街19號2樓", phone: "03-6686335", hours: "約 20:00–03:00（週一休）", awards: ["2020 德國 iF 設計獎"], note: "竹科金山街知名酒吧，以李白〈將進酒〉為題的中國風空間曾獲德國 iF 設計獎，擅長琴酒基底與茶酒調和，竹科人下班微醺首選。"},
  {name: "Bar Resurf", city: "新竹市", district: "東區", type: "經典特調", purpose: "一個人", style: "沉靜獨酌系", price: 2, address: "新竹市東區民主路107號", phone: "03-5428282", hours: "約 20:00–03:00（週日一休）", rating: 4.8, note: "僅接受兩人以內入座的獨特規定，每個吧台座位配置聚光燈，讓人專注於杯中酒與自己，被譽為留給自己獨處與對話的酒吧。"},
  {name: "inBush – bar, café, flower", city: "新竹市", district: "東區", type: "特調", purpose: "聚會或一個人", style: "英倫風、花藝×咖啡×酒吧", price: 2, address: "新竹市東區長春街60號", phone: "03-6662592", hours: "10:00–01:00（調酒 18:00 起；週一休）", note: "結合花店、咖啡廳與酒吧的複合式空間，白天供應手沖咖啡與花藝課程，夜晚轉為清新系調酒酒吧。"},

  // ───── 新竹縣 ─────
  {name: "Bar Balcony 陽台酒吧", city: "新竹縣", district: "竹北市", type: "特調", purpose: "聚會或一個人", style: "沙發慵懶系創意調酒", price: 2, address: "新竹縣竹北市勝利七街一段248號", phone: "03-6681231", hours: "約 19:30–03:00", note: "2020年底進駐竹北高鐵特區，開幕不到一年即成在地知名酒吧，重視調酒層次與創新口味開發，二樓陽台區氣氛放鬆。"},
  {name: "Bar Neat", city: "新竹縣", district: "竹北市", type: "特調", purpose: "聚會", style: "工地鷹架反差、精緻餐酒館", price: 2, address: "新竹縣竹北市莊敬七街43號", phone: "03-6688997", hours: "約 18:00 起至午夜（週日休）", note: "外觀刻意以工地鷹架包覆製造反差，調酒師搭配曾任職紐約、新加坡米其林一星餐廳的主廚，調酒與精緻料理並重，竹科人微醺基地。"},
  {name: "橋下2.0 Restaurant & Bar", city: "新竹縣", district: "竹北市", type: "特調", purpose: "聚會", style: "輕奢餐酒館、隱藏酒吧「薀室」", price: 3, address: "新竹縣竹北市嘉豐北路62號", phone: "03-5505252", hours: "午餐 12:00–14:00、晚間 17:30 起至深夜", note: "竹北知名餐酒館「橋下」進化版，鄰近新竹高鐵站，內有植栽系隱藏酒吧「薀室」，是竹北約會聚餐熱門選擇。"},

  // ───── 苗栗縣 ─────
  {name: "上癮餐酒館 Obsession Bar", city: "苗栗縣", district: "竹南鎮", type: "特調", purpose: "聚會", style: "黑色貨櫃屋餐酒館", price: 2, address: "苗栗縣竹南鎮公北一路151號", phone: "0901-193-949", hours: "17:00–02:00", note: "竹南運動公園旁醒目的黑色貨櫃屋餐酒館，以浮誇神燈調酒與乾燥花夢幻雞尾酒聞名，週六有駐唱，竹南頭份一帶人氣酒吧。"},
  {name: "紳OWL餐酒館", city: "苗栗縣", district: "頭份市", type: "經典特調", purpose: "聚會", style: "質感餐酒館", price: 2, hours: "營業至02:00", note: "頭份在地人私藏的質感餐酒館，空間寬敞、燈光柔和，Old Fashioned 等經典調酒水準被評為頭份數一數二。"},

  // ───── 台中市 ─────
  {name: "Vender 販", city: "台中市", district: "西區", type: "特調", purpose: "聚會或一個人", style: "Speakeasy、南洋風", price: 3, address: "台中市西區五權西四街118號", phone: "04-2372-5875", hours: "週日至四 18:00–02:00、週五六至03:00", awards: ["Asia's 50 Best Bars 2025 #20（台灣最佳）","World's 50 Best Bars 2025 #74"], note: "隱身美術館綠園道旁巨型販賣機後的話題酒吧，新加坡籍主理人以創意調酒搭配肉骨茶等星馬料理，台中唯一連年入選亞洲五十大酒吧的名店。"},
  {name: "栖 Habitatto", city: "台中市", district: "西區", type: "特調", purpose: "聚會或一個人", style: "老宅、茶酒", price: 2, address: "台中市西區民權路217巷22號", hours: "19:00–02:00（週二休）", note: "由七十年老屋改建的茶酒吧，以台灣茶入酒的特調聞名，木質老宅氛圍靜謐，設有包廂。"},
  {name: "Bar Saito 齋藤", city: "台中市", district: "西區", type: "經典", purpose: "一個人", style: "日式正統酒吧", price: 2, address: "台中市西區華美街412-1號", hours: "19:00–02:00", note: "台中正統日式 Bar 代表，源自東京的吧檯文化，以經典調酒與威士忌為主，僅約12席、全店禁菸，適合安靜獨酌。"},
  {name: "安慰劑臺中店 Placebo Taichung", city: "台中市", district: "西屯區", type: "特調", purpose: "聚會", style: "中式復古客棧風 Speakeasy", price: 3, address: "台中市西屯區文心路三段91-9號", phone: "04-2317-6661", hours: "20:00–02:00（週五六至03:00，週二休）", note: "知名品牌「安慰劑」台中店，以東方美學客棧酒樓為主題，招牌碗裝 punch 與創意調酒，低消500元/人。"},
  {name: "Svart Hull 黑洞", city: "台中市", district: "西屯區", type: "經典特調", purpose: "聚會或一個人", style: "星際主題、無酒單客製", price: 2, address: "台中市西屯區何厝街86號", hours: "週一至四 20:00–02:00、週五六至03:00", note: "銀河系主題酒吧，無固定酒單、由調酒師依喜好客製，曾以台灣蒜頭酒入酒的特調引起話題。"},
  {name: "好吧 Goût Bar", city: "台中市", district: "西區", type: "經典特調", purpose: "聚會或一個人", style: "隱藏式入口、客製調酒", price: 2, address: "台中市西區存中街46號", hours: "18:00–01:00", note: "美術館園道周邊的隱藏系酒吧，入口低調，以客製化調酒與輕鬆氛圍受在地酒客歡迎。"},
  {name: "SOAK Taichung", city: "台中市", district: "西屯區", type: "特調", purpose: "聚會", style: "室內泳池、熱帶派對風", price: 2, address: "台中市西屯區河南路三段120號7樓", hours: "20:00–02:30", note: "以室內泳池造景與熱帶島嶼風設計聞名的話題酒吧，適合團體聚會與拍照打卡。"},
  {name: "Draft Land Taichung", city: "台中市", district: "西區", type: "特調", purpose: "聚會或一個人", style: "汲飲式雞尾酒", price: 1, address: "台中市西區英才路534號 PARK2草悟廣場 B1", hours: "週日至四 12:00–21:00、週五六至22:30", note: "亞洲首創汲飲式雞尾酒品牌的台中店，進駐 PARK2 草悟廣場，推出台中限定酒款，下午就能開喝。"},
  {name: "Bar 明治", city: "台中市", district: "西區", type: "經典", purpose: "一個人", style: "日式經典、高CP值", price: 1, address: "台中市西區中美街399號", hours: "19:00–04:00（週一休）", note: "隱藏於前居酒屋店面的日系經典酒吧，調酒師來自日本，以價格實惠的經典調酒與鮮果調酒著稱，營業至凌晨四點。"},
  {name: "KOLEN Cuisine & Drink", city: "台中市", district: "北區", type: "經典特調", purpose: "聚會或一個人", style: "明亮現代、葡萄酒調酒", price: 2, address: "台中市北區忠太東路113號", hours: "18:00–02:00", note: "台中北區高人氣新銳酒吧，以客製調酒、葡萄酒基底調酒與自然酒搭餐聞名，空間明亮不同於傳統暗黑酒吧。"},
  {name: "舟舟 Bar Boat", city: "台中市", district: "西區", type: "特調", purpose: "聚會或一個人", style: "創意調酒、星空迷幻風", price: 2, address: "台中市西區精誠一街4號", hours: "20:00–02:00", note: "精誠商圈人氣創意調酒吧，以迷幻星空氛圍與視覺系特調受年輕客群喜愛。"},
  {name: "青AO", city: "台中市", district: "西區", type: "特調", purpose: "聚會或一個人", style: "康普茶酒、清新風", price: 2, address: "台中市西區美村路一段335號", hours: "週二至日 18:30–01:00", note: "以自釀康普茶入酒為主軸的特色酒吧，酸香清爽的茶酒調飲是招牌，媒體評為台中必訪風格酒吧。"},
  {name: "Matches", city: "台中市", district: "西區", type: "經典特調", purpose: "聚會", style: "華麗餐酒館", price: 3, address: "台中市西區東興路三段238號2樓", hours: "18:00–01:00（週五六至02:00）", note: "裝潢華麗的高質感餐酒館型酒吧，調酒與餐點兼備，適合約會與多人聚會。"},

  // ───── 彰化縣 ─────
  {name: "GUTS Cocktail Bar 蓋茲", city: "彰化縣", district: "彰化市", type: "經典特調", purpose: "聚會或一個人", style: "茶酒、專業雞尾酒吧", price: 2, address: "彰化縣彰化市吉祥街3號", phone: "0928-962-999", hours: "週日至四 18:30–01:00、週五六至02:00", note: "彰化市代表性專業調酒吧，以 TWG 茶葉特製茶酒（皇家婚禮、經典1837等）聞名，一個人小酌也自在。"},
  {name: "勝豐吧 Home Bar Lukang", city: "彰化縣", district: "鹿港鎮", type: "啤酒", purpose: "聚會或一個人", style: "百年老屋、精釀啤酒", price: 2, address: "彰化縣鹿港鎮民族路131號", phone: "04-7785232", hours: "18:00–00:00（週四休）", note: "由許家後代與「鹿港囝仔」團隊改造百年老屋而成的精釀啤酒吧，供各國精釀、威士忌並提供老屋導覽，鹿港地方創生代表店家。"},
  {name: "老屋舊時光茶酒所", city: "彰化縣", district: "彰化市", type: "特調", purpose: "聚會", style: "老宅、茶酒、音樂", price: 1, note: "彰化南瑤宮商圈的老宅改建小酒館，結合調酒、茶飲、炸物與音樂，彰化夜貓族的人氣宵夜小酌據點。"},

  // ───── 南投縣 ─────
  {name: "Michael Bar", city: "南投縣", district: "南投市", type: "經典", purpose: "一個人", style: "老派酒吧、爵士", price: 2, address: "南投縣南投市大同街148號", phone: "049-2238123", hours: "19:00–02:00", note: "自1990年營業至今的南投市老酒吧，木質吧檯、昏黃燈光配爵士樂，延續創始人 Michael 的經典調酒，南投低調老酒吧代表。"},
  {name: "漫。島美式餐酒館 ChillBar", city: "南投縣", district: "埔里鎮", type: "經典特調", purpose: "聚會", style: "美式餐酒館、煙燻烤肉", price: 2, address: "南投縣埔里鎮中山路二段436號", phone: "0988-664-331", hours: "平日 17:00–01:00、週五六 15:00 起（週四休）", note: "埔里少見的美式餐酒館，招牌島主特調與煙燻肉排，英倫雅痞氛圍越夜越熱鬧，埔里夜晚小酌首選之一。"},

  // ───── 雲林縣 ─────
  {name: "艾澤拉斯小酒館", city: "雲林縣", district: "斗六市", type: "經典特調", purpose: "聚會或一個人", style: "客製調酒、在地食材", price: 2, address: "雲林縣斗六市內環路772號", phone: "0925-006-289", hours: "週日至四 20:00–02:00、週五六至03:00（週二休）", note: "斗六代表性調酒吧，致力將雲林在地食材融入雞尾酒並提供客製專屬調酒，調酒師會細心解說風味層次，新手友善。"},
  {name: "Moon Lounge 月廊天台酒吧", city: "雲林縣", district: "虎尾鎮", type: "經典特調", purpose: "聚會", style: "高空天台酒吧", price: 2, address: "雲林縣虎尾鎮信義路69號10樓", phone: "05-6362242", hours: "20:00–02:00", note: "位於虎尾春秋文創設計旅店10樓的半露天高空酒吧，可俯瞰虎尾夜景，人氣調酒有橙柚紅、青蓮居士等，雲林百選打卡地標。"},

  // ───── 嘉義市 ─────
  {name: "秉森酒室 Bar Bingsen", city: "嘉義市", district: "西區", type: "經典特調", purpose: "一個人", style: "日式沉靜酒吧", price: 2, address: "嘉義市西區林森西路528號", hours: "19:30–01:30（週二三休）", note: "嘉義火車站旁的日式酒吧，入座先奉熱毛巾，暖黃燈光與木質空間隔絕車馬喧囂，調酒師細問喜好後推薦，適合獨自放鬆。"},
  {name: "COP bar - Cocktails Of Pioneers", city: "嘉義市", district: "西區", type: "特調", purpose: "聚會", style: "現代創意、在地食材調酒", price: 2, address: "嘉義市西區西門街54-1號", hours: "19:30–02:00", note: "以「敬所有先驅者」為題的質感酒吧，用阿里山高山茶、民雄土鳳梨、北港麻油等在地素材調製創意調酒，吧台投影水光效果吸睛。"},
  {name: "斗酒 BAR DOUJIOU", city: "嘉義市", district: "東區", type: "特調", purpose: "聚會", style: "70年老宅懷舊", price: 2, address: "嘉義市東區成仁街82號", hours: "19:30–02:30（週一休）", note: "前身為籐椅傢俱店的70年老屋改建，保留老宅風貌，調酒與餐點兼具、附包廂，嘉義聚會小酌的口碑店。"},
  {name: "CASA bar", city: "嘉義市", district: "東區", type: "特調", purpose: "聚會", style: "科幻未來系、冷調金屬", price: 2, address: "嘉義市東區光彩街132號", hours: "19:00–01:00（週日一休）", note: "嘉義少見的科幻未來風酒吧，冷派金屬空間設計視覺效果強烈，以創意特調聞名。"},

  // ───── 台南市 ─────
  {name: "Bar TCRC 前科累累俱樂部", city: "台南市", district: "中西區", type: "特調", purpose: "聚會或一個人", style: "老屋無酒單創意調酒", price: 2, address: "台南市中西區新美街117號", phone: "06-2228716", hours: "週一至四 20:00–02:00、週五六至03:00（週日休）", awards: ["Asia's 50 Best Bars 多次入選（2021 #23）"], note: "台南酒吧代表、南台灣揚名國際的老宅酒吧，無固定酒單依客人喜好客製，招牌如洛神蜜餞入酒的「府城漫步」。每月1日開放當月線上訂位，一位難求。"},
  {name: "Phowa 頗瓦", city: "台南市", district: "中西區", type: "特調", purpose: "聚會", style: "廟宇民俗風餐酒館", price: 2, address: "台南市中西區新美街121號", phone: "06-2231020", hours: "19:00–01:00（週日休）", note: "TCRC 團隊三店，以台灣廟宇香火意象打造神秘氛圍，臭豆腐漢堡排等台味餐搭配創意調酒是招牌。"},
  {name: "Bar Home", city: "台南市", district: "中西區", type: "特調", purpose: "聚會或一個人", style: "老洋房歐式復古、無酒單", price: 2, address: "台南市中西區中山路23巷1號", phone: "06-2232869", hours: "19:00–01:00（週六 18:00 起）", rating: 4.6, note: "TCRC 主理人的二店，老洋房改建、歐式宮廷復古氛圍，全預約制，無酒單依喜好客製，甜點布丁與麵食也極有口碑。"},
  {name: "酣呷餐酒 The Han-Jia", city: "台南市", district: "南區", type: "經典特調", purpose: "聚會", style: "威士忌餐酒館、電影主題調酒", price: 3, address: "台南市南區西門路一段669號", phone: "06-2257669", hours: "週日至四 18:00–00:00、週五六至01:00", awards: ["Asia's 50 Best Bars 2026 #41","主理人為 2022 World Class 台灣冠軍"], note: "挑高老屋搭配水晶吊燈與威士忌酒牆，調酒以電影為題、敘事感強，2026年新入榜亞洲50大酒吧，台南餐酒搭配指標。"},
  {name: "Moonrock", city: "台南市", district: "北區", type: "特調", purpose: "聚會或一個人", style: "老宅茶酒、台式茶館意象", price: 2, address: "台南市北區成功路22巷42弄13號", phone: "06-2229528", hours: "週一至六 20:00–02:00（週日休）", awards: ["Asia's 50 Best Bars 2025 #42"], note: "由 TCRC 出身調酒師創立，藏身巷弄老宅，以台灣茶文化為靈感結合音樂與光影敘事，調酒層次如分子料理，熱門到幾乎只能預約。"},
  {name: "赤崁中藥行", city: "台南市", district: "中西區", type: "特調", purpose: "聚會", style: "中藥行主題 Speakeasy、琴酒", price: 2, address: "台南市中西區赤嵌街45巷3號", phone: "06-2219599", hours: "20:00–02:00（週五六至03:00，週二休）", note: "台南第一家琴酒吧，以50年代中藥房為場景，復古藥櫃與算盤營造懷舊氛圍，招牌為枸杞茱萸等中藥材入酒的調飲，近赤崁樓常一位難求。"},
  {name: "Bar Mozaiku 馬賽克酒吧", city: "台南市", district: "北區", type: "特調", purpose: "聚會或一個人", style: "日式庭院、無酒單客製", price: 2, address: "台南市北區國華街四段5巷15號", phone: "06-2223098", hours: "20:00–03:00（週二休）", note: "近神農街的日式簡約老屋酒吧，無酒單、由調酒師依口味客製，不接受訂位僅現場候位，台南深夜無酒單酒吧代表之一。"},
  {name: "籠裏 Bar Lonely", city: "台南市", district: "中西區", type: "特調", purpose: "一個人", style: "日式昭和老宅、靜謐", price: 2, address: "台南市中西區民生路一段157巷11號1樓", phone: "0966-022075", hours: "20:00–01:00（週四、日休）", note: "老屋改建的日系昭和風酒吧，附和室座位，氣氛低調沉靜，擅長茶酒與季節水果調酒，適合一個人的深夜微醺。"},
  {name: "Bar INFU", city: "台南市", district: "中西區", type: "特調", purpose: "聚會或一個人", style: "歐洲古董風、浸漬調酒", price: 2, address: "台南市中西區忠義路二段84巷63號", phone: "06-2235639", note: "店名取自 Infuse 浸漬手法，以水果、香料浸漬基酒層層堆疊風味，老宅內滿是歐洲古董陳設（原羅東名店 Bar Sumi 搬遷改名）。"},
  {name: "Taleland 樂島", city: "台南市", district: "中西區", type: "特調", purpose: "聚會或一個人", style: "老宅新古典、台灣茶調酒", price: 2, address: "台南市中西區中正路150巷5號", hours: "19:00–02:00（週二休）", note: "保留昭和檜木天花板與百年八角窗的老宅酒吧，主理人環島尋訪茶園、以台灣茶入酒為品牌核心，招牌如鐵觀音調製的 Good Luck。"},
  {name: "在島之後 After Island", city: "台南市", district: "東區", type: "特調", purpose: "聚會", style: "餐酒館、浮誇系特調", price: 2, address: "台南市東區東寧路201巷121號", phone: "06-2002076", hours: "18:00–02:00", note: "台南東區人氣餐酒館，無酒單華麗特調搭配燉飯、塔可飯等實力餐點，並不定期有樂團演出，聚餐約會熱門、建議先訂位。"},

  // ───── 高雄市 ─────
  {name: "MALTAIL", city: "高雄市", district: "前金區", type: "經典特調", purpose: "聚會或一個人", style: "威士忌×調酒", price: 3, address: "高雄市前金區中華四路349之1號", phone: "07-2218086", hours: "20:00–02:00", awards: ["Asia's 50 Best Bars 2025 #75（高雄首度入榜）"], note: "由烈酒作家創立，一樓供應汲飲雞尾酒、二樓為威士忌與經典調酒，以單一麥芽威士忌重新詮釋亞洲風味，全預約制，高雄登上亞洲榜的代表酒吧。"},
  {name: "Marc L³", city: "高雄市", district: "前金區", type: "特調", purpose: "聚會", style: "Fine Dining 餐酒", price: 3, address: "高雄市前金區仁義街231號", hours: "週二至六 18:00–22:00（週日一休）", awards: ["米其林指南入選餐廳"], note: "現代歐陸菜餐廳，以在地時令食材做9道式套餐，米其林指南特別點名其自行設計的調酒值得一試，高雄餐酒搭配指標。"},
  {name: "上善若水 Goodness Bistro", city: "高雄市", district: "苓雅區", type: "經典特調", purpose: "聚會或一個人", style: "民宅隱藏系、琴酒威士忌", price: 2, address: "高雄市苓雅區福建街221號", phone: "07-536-8150", hours: "20:00–03:00", rating: 4.6, note: "隱身文化中心一帶民宅的無酒單酒吧，琴酒與威士忌品項豐富，調酒師依喜好客製、裝飾精緻，不接受電話預約、常需排隊。"},
  {name: "三千 - Atman Space", city: "高雄市", district: "苓雅區", type: "經典特調", purpose: "聚會或一個人", style: "文青工業復古、日咖夜酒", price: 2, address: "高雄市苓雅區民權一路94號", phone: "0902-312-756", hours: "19:00–02:00", rating: 4.7, note: "白日咖啡、入夜化身酒吧的文青空間，以毛筆點餐、藏書與黑膠聞名，設有威士忌酒牆，高雄低調卻口碑極佳的小酒館。"},
  {name: "行者酒吧 The Walkers", city: "高雄市", district: "三民區", type: "經典", purpose: "聚會或一個人", style: "日式酒吧、忠於經典", price: 2, address: "高雄市三民區旅順街8號", phone: "0968-689-417", hours: "週三至日 20:00–02:00", rating: 4.9, note: "白天是自家烘豆的泰迪咖啡商行，入夜轉場為日式酒吧，走純粹經典調酒路線，單杯約280–350元，評價在高雄名列前茅。"},
  {name: "Bar Diary", city: "高雄市", district: "鼓山區", type: "經典特調", purpose: "聚會或一個人", style: "無酒單威士忌吧、深夜營業", price: 2, address: "高雄市鼓山區富農路80號", phone: "07-5224467", hours: "21:00–05:00", rating: 4.4, note: "凹子底一帶的隱密酒吧，營業到清晨五點、是調酒師與夜班族下班後的去處；二樓店中店以威士忌老酒為主、僅週五六開放。"},
  {name: "Old.Trick 佬掉牙商行", city: "高雄市", district: "鹽埕區", type: "特調", purpose: "聚會或一個人", style: "復古懷舊、無酒單", price: 2, address: "高雄市鹽埕區大勇路68號", phone: "07-551-9555", hours: "週日至四 19:00–02:00、週五六至03:00", rating: 4.3, note: "捷運鹽埕埔站旁的老派懷舊酒吧，無酒單、由調酒師依需求創作特調（約250–350元），可攜外食，鹽埕夜生活代表店家之一。"},
  {name: "萬.吧 ONE.Bar", city: "高雄市", district: "苓雅區", type: "特調", purpose: "聚會或一個人", style: "日本昭和復古", price: 2, address: "高雄市苓雅區青年一路261巷1號", phone: "07-331-3322", hours: "酒吧 20:00–02:00", rating: 4.4, note: "老公寓改建的昭和時代風酒吧，果糖、果乾、果醬等調酒材料皆由調酒師親手熬煮釀造，座位設計讓人安靜沉浸。"},
  {name: "Marsalis Bar 馬沙里斯爵士酒館", city: "高雄市", district: "新興區", type: "經典", purpose: "聚會或一個人", style: "歐風爵士酒吧、現場演奏", price: 2, address: "高雄市新興區中正四路71號2樓", phone: "07-281-4078", hours: "週三四日 14:00–00:00、週五六至01:00（週一二休）", note: "高雄首家爵士酒吧，黑膠與現場爵士演出搭配精緻經典調酒，並供烈酒與雪茄，高雄老牌且最具代表性的音樂酒吧。"},
  {name: "TimeS Antique & Bar 時光古董酒吧", city: "高雄市", district: "鼓山區", type: "特調", purpose: "聚會", style: "哈瑪星老屋、古董復古風", price: 2, address: "高雄市鼓山區臨海一路20-7號", phone: "0963-757-838", hours: "週二至日 18:00–01:00（週一休）", rating: 4.8, note: "位於哈瑪星的地下復古酒吧，黑膠唱片與古董燈飾營造時光倒流氛圍，供應調酒與精釀啤酒，打狗港區散步後小酌熱門選擇。"},

  // ───── 屏東縣 ─────
  {name: "30M BAR", city: "屏東縣", district: "恆春鎮", type: "特調", purpose: "聚會或一個人", style: "海洋／潛水主題", price: 2, address: "屏東縣恆春鎮恆南路125巷6號", phone: "08-888-1129", hours: "20:00–02:00（週二休）", note: "恆春最具代表性的酒吧之一，老闆為職業潛水員，酒單緊扣海洋與環境保育主題，招牌有在地青龍糯米椒調製的「小青龍」。"},
  {name: "恆春3000啤酒博物館", city: "屏東縣", district: "恆春鎮", type: "啤酒", purpose: "聚會", style: "精釀啤酒博物館", price: 1, address: "屏東縣恆春鎮草埔路29-1號", hours: "11:00–18:00（週四休）", note: "收藏逾3000只世界各地啤酒杯的啤酒博物館，供應墾丁南灣愛爾、司陶特黑啤等自釀精釀，門票100元可抵飲品，恆春墾丁喝啤酒地標。"},
  {name: "如煙人文餐酒館", city: "屏東縣", district: "屏東市", type: "特調", purpose: "聚會", style: "日式居酒屋餐酒、眷村老屋", price: 2, address: "屏東縣屏東市勝義巷10號（勝利星村內）", phone: "08-7321527", hours: "週日至四 17:00–24:00、週五六至01:00（週一休）", note: "位於勝利星村日式老屋群中，宛如《華燈初上》場景的居酒屋餐酒館，日式定食搭配特色調酒，屏東市區最具話題的微醺去處。"},

  // ───── 宜蘭縣 ─────
  {name: "The Roof 190 星空酒吧", city: "宜蘭縣", district: "羅東鎮", type: "特調", purpose: "聚會", style: "飯店頂樓高空景觀", price: 2, address: "宜蘭縣羅東鎮站東路190號（村却國際溫泉酒店頂樓）", phone: "03-9057988", hours: "約 16:00–24:00", note: "位於羅東最高樓村却國際溫泉酒店頂樓，可360度眺望蘭陽平原夜景，被媒體譽為媲美曼谷高空酒吧，非房客低消300元。"},
  {name: "Maison 迴家酒館", city: "宜蘭縣", district: "羅東鎮", type: "特調", purpose: "聚會或一個人", style: "浮誇擺盤創意調酒", price: 2, address: "宜蘭縣羅東鎮純精路三段256號", note: "羅東首間質感系酒吧，主打結合宜蘭在地特產的浮誇系調酒如「宜蘭發大財」，以乾冰、鳥籠、迷你浴缸等擺盤聞名。"},
  {name: "飲廊 Corridor", city: "宜蘭縣", district: "羅東鎮", type: "特調", purpose: "聚會", style: "輕工業×花草森林系餐酒館", price: 2, address: "宜蘭縣羅東鎮公正街56號", phone: "03-9550557", hours: "約 11:00–21:30，週五六至凌晨（週二休）", note: "羅東夜市旁巷內的森林系玻璃屋餐酒館，白天供餐、夜晚轉為微醺空間，以宜蘭在地食材入菜與特調聞名。"},
  {name: "西江水坊", city: "宜蘭縣", district: "礁溪鄉", type: "特調", purpose: "聚會或一個人", style: "中式禪意茶酒", price: 2, address: "宜蘭縣礁溪鄉德陽路24巷6號", phone: "03-9880266", hours: "約 19:00–00:00（週五六至01:00；週二三休）", note: "由專業評茶師與調酒師共同主理，以「以茶會酒」為概念的中式古典茶酒吧，冠軍茶入酒並入菜，一位難求的礁溪代表性酒吧。"},
  {name: "Bar 清溪（上善若水）", city: "宜蘭縣", district: "礁溪鄉", type: "特調", purpose: "聚會或一個人", style: "中式復古、台菜餐酒", price: 2, address: "宜蘭縣礁溪鄉中山路二段156號", phone: "0921-523-435", hours: "約 15:00–00:00（週三休）", note: "近礁溪火車站與湯圍溝溫泉公園的復古風酒吧，古董傢俱與留聲機營造懷舊氛圍，招牌皮蛋入酒調酒「傳承」搭配手做台式料理。"},

  // ───── 花蓮縣 ─────
  {name: "和嶼 Peace Isle", city: "花蓮縣", district: "花蓮市", type: "經典特調", purpose: "聚會或一個人", style: "質感都會酒吧", address: "花蓮縣花蓮市光復街80號1樓", phone: "03-8320183", hours: "約 19:00–01:00", note: "花蓮市區指標性質感酒吧，多篇媒體與在地跑吧文章列為花蓮必訪，調酒師可依客人喜好客製，威士忌基底調酒選擇多。"},
  {name: "島東譯電所", city: "花蓮縣", district: "花蓮市", type: "特調", purpose: "聚會或一個人", style: "復古獵奇藝文空間", address: "花蓮縣花蓮市化道路18-1號", hours: "10:30–22:30", note: "花蓮最具代表性的怪奇復古酒吧，招牌為洛神花琴酒馬告、烏梅汁蘭姆酒等在地特色調酒。2025年底搬遷至美崙化道路現址。"},
  {name: "牧羊人酒吧 Bar Shepherd", city: "花蓮縣", district: "新城鄉", type: "特調", purpose: "聚會", style: "七星潭海邊露天餐酒館", address: "花蓮縣新城鄉大漢村七星街9號", phone: "0925-810-413", hours: "19:00–02:00（週一二休）", note: "花蓮最靠海的酒吧，坐在七星潭旁聽海浪看星星；可客製「沒有名字的調酒」，並供應窯烤料理。"},
  {name: "琴詩酒吧 Ginsman Bar", city: "花蓮縣", district: "花蓮市", type: "特調", purpose: "聚會或一個人", style: "無酒單琴酒吧", address: "花蓮縣花蓮市新港街62號", phone: "03-8338801", hours: "19:00–02:00（週二休）", rating: 4.6, ratingCount: 417, note: "以琴酒為主軸的無酒單酒吧，調酒師依客人偏好的酸甜、香氣與基底客製，氣氛安靜放鬆，適合一人靜飲。"},
  {name: "奉珠吧", city: "花蓮縣", district: "吉安鄉", type: "特調", purpose: "聚會", style: "茶酒餐酒館、家常菜", address: "花蓮縣吉安鄉福興六街38號", hours: "約 19:00–01:00（預約制）", note: "由兄弟與媽媽「奉珠」共同經營，擅長以茶葉與水果入酒，搭配整桌家常創意菜，花蓮跑吧名單常客；採預約制。"},

  // ───── 台東縣 ─────
  {name: "Bar Cynic 吧蟲", city: "台東縣", district: "台東市", type: "特調", purpose: "聚會或一個人", style: "無菜單、在地食材入酒", address: "台東縣台東市和平街118號", hours: "20:00–02:00", awards: ["Tatler Best Taiwan 2025 台灣 Top 20 酒吧"], note: "主理人曾獲格蘭菲迪世界調酒實驗賽冠軍，無固定酒單，以台東在地農產客製調酒，被稱為台東都市傳說級酒吧。"},
  {name: "吧東 Bar tung", city: "台東縣", district: "台東市", type: "特調", purpose: "聚會或一個人", style: "日式老屋餐酒館", address: "台東縣台東市福建路307號", hours: "週日至四 19:00–00:30；週五六至02:30（週一休）", note: "隱身巷弄的日式建築酒吧，招牌為把檳榔香氣化為液體的「檳榔特調」與洛神調酒，充滿部落與台東風味。"},
  {name: "康杯 COMEBACK", city: "台東縣", district: "台東市", type: "特調", purpose: "聚會或一個人", style: "茶酒、深夜小酒吧", address: "台東縣台東市福建路217號", phone: "089-310857", hours: "週日至四 20:00–03:00；週五六至04:00", note: "以台東鹿野紅烏龍茶特調茶酒聞名，也有威士忌與小米酒結合的調酒，在地人深夜小酌的人氣店。"},
  {name: "寶桑吧（The Gaya Hotel）", city: "台東縣", district: "台東市", type: "經典特調", purpose: "聚會", style: "飯店 Lounge、週末 Live Band", address: "台東縣台東市新生路169號", phone: "089-341593", hours: "20:00–03:00", note: "The Gaya Hotel 附設酒吧，運用東部特色食材調酒，週五六晚間有現場演奏可點歌，台東市區熱門夜生活據點。"},
  {name: "喨哥Beer", city: "台東縣", district: "台東市", type: "啤酒", purpose: "聚會或一個人", style: "精釀啤酒、深夜食堂式小店", address: "台東縣台東市中正路191號", hours: "17:00–00:00（週日休）", rating: 4.9, note: "老闆喨哥親選比利時與各國精釀啤酒，被媒體形容為台東版深夜食堂，台東精釀啤酒的代表店家。"},

  // ───── 澎湖縣 ─────
  {name: "Beacon 說酒人", city: "澎湖縣", district: "馬公市", type: "啤酒", purpose: "聚會或一個人", style: "咾咕石老宅精釀啤酒吧", price: 2, address: "澎湖縣馬公市臨海路15-3號", hours: "19:00–00:00（季節性營業，冬季休）", note: "澎湖第一家專營精釀啤酒的酒吧，隱身鬧區巷弄的60年老宅內，供應歐美與台灣精釀並提供創意調酒。"},
  {name: "弗洛伊得音樂·餐酒 Freud Bar", city: "澎湖縣", district: "馬公市", type: "經典特調", purpose: "聚會", style: "美式復古音樂餐酒館", price: 2, address: "澎湖縣馬公市新生路2號", phone: "06-9264166", hours: "18:30–02:30", note: "1991年開業、經營超過30年的澎湖第一間 PUB，昏黃燈光與老照片營造老酒館氛圍，調酒與餐點皆有口碑。"},
  {name: "蓓菈 BELLA 調酒專賣所", city: "澎湖縣", district: "馬公市", type: "特調", purpose: "聚會或一個人", style: "隱藏版創意調酒吧", address: "澎湖縣馬公市文康街16號", phone: "0937-605-093", hours: "19:00–02:30", note: "距觀音亭步行約五分鐘的隱藏版酒吧，以創意調酒與聽故事般的吧檯互動聞名，澎湖夜生活口碑名店。"},
  {name: "Swave 微浮酒吧", city: "澎湖縣", district: "馬公市", type: "經典特調", purpose: "聚會", style: "飯店 Lounge、Live Band", price: 3, address: "澎湖縣馬公市新店路197號B2（福朋喜來登）", phone: "06-9271005", hours: "約 20:00–01:00", note: "藏身福朋喜來登地下二樓，被稱為澎湖最時尚高檔的酒吧，有國際樂團現場演唱與半開放包廂。"},

  // ───── 金門縣 ─────
  {name: "夢酒館 MOJO", city: "金門縣", district: "金城鎮", type: "特調", purpose: "聚會或一個人", style: "閩式古厝、高粱調酒", price: 2, address: "金門縣金城鎮莒光路110巷4號", phone: "0911-948-711", hours: "19:30–00:30（週二休）", note: "返鄉青年經營，以58度金門高粱設計調酒，招牌「No.16」融合高粱與熱帶水果，金門調酒吧代表。"},
  {name: "金城飯店｜金門威士忌博物館", city: "金門縣", district: "金城鎮", type: "經典特調", purpose: "聚會或一個人", style: "1842年閩式古厝×英式酒吧", address: "金門縣金城鎮中興路67巷10-1號", phone: "0971-882-587", hours: "19:30–00:00", note: "在1842年閩式建築中打造英式酒吧氛圍，館藏威士忌與高粱，提供創意高粱威士忌調酒，金門夜生活新去處。"},
  {name: "遇見 Meet Bar", city: "金門縣", district: "金寧鄉", type: "特調", purpose: "聚會", style: "高粱特調、聽故事式調酒", address: "金門縣金寧鄉環島北路一段369號1樓", phone: "082-316439", hours: "20:00–04:00（週二休）", note: "以金門高粱特調聞名，招牌「好酒不見」以58度高粱混龍舌蘭，調酒師會依顧客心情量身打造調酒。"},
  {name: "帕堤 Let's party", city: "金門縣", district: "金城鎮", type: "特調", purpose: "聚會", style: "深夜美式酒吧餐廳", address: "金門縣金城鎮西海路三段72巷3弄5號", phone: "082-329147", hours: "20:00–01:00", note: "金門深夜續攤人氣店，高粱特調以檸檬、紅茶淡化辛辣感，搭配高粱嗆蟹、高粱餛飩泡麵等下酒菜。"},
  {name: "談醺室", city: "金門縣", district: "金城鎮", type: "啤酒", purpose: "一個人", style: "金門在地精釀、風獅爺主題", address: "金門縣金城鎮莒光路118號", hours: "17:00–21:00", note: "金門首家精釀啤酒品牌門店，首創高粱啤酒，推出烈火獅、神風獅等風獅爺主題酒款，金門微醺新據點。"},
];
